### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ooshnoo** [haircut/better-jamf-policy-deferral#11]
**Describe the bug**
```
Script result: Traceback (most recent call last):
  File "/Library/Application Support/JAMF/tmp/Defer Software Updates", line 29, in <module>
    from AppKit import NSWorkspace
ModuleNotFoundError: No module named 'AppKit'
```

**Python 3**

_Note:_ Issues opened without specifying one of the following options will be ignored.

- [ ] I am using the [macadmins Python](https://github.com/macadmins/python) distribution that I installed on the affected Mac.
- [X] I am using a Python 3 runtime I installed myself, and I updated the script's shebang to point to the that `python3` binary.

**To Reproduce**
I run the prompt policy that calls the script.  Get the following error:

```
Script result: Traceback (most recent call last):
  File "/Library/Application Support/JAMF/tmp/Defer Software Updates", line 29, in <module>
    from AppKit import NSWorkspace
ModuleNotFoundError: No module named 'AppKit'
```

What am I missing?  running macOS 12.3.1

**Comment by ooshnoo** [comment]
Also tried it with the macadmins python and reverted script shebang.  no change.
